# This is a basic workflow to help you get started with Actions
name: Hello World
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello welcome to git actions"
